version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - ./packages:/app/packages
      - frontend-node-modules:/app/apps/frontend/node_modules
      - packages-node-modules:/app/packages/node_modules

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - FRONTEND_URL=http://frontend:3000
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./packages:/app/packages
      - backend-node-modules:/app/apps/backend/node_modules
      - packages-node-modules:/app/packages/node_modules
      - sqlite-data:/app/apps/backend/data

volumes:
  frontend-node-modules:
  backend-node-modules:
  packages-node-modules:
  sqlite-data: 